import json, os


def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(obj, path, indent=2):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=indent)
    return path


def save_js(obj, var_expr, path, header="// Generated by tools/mocap/capture_moves.py — do not edit by hand."):
    """Write `<var_expr> = <compact-json>;` (e.g. var_expr="window.RODA_MOCAP['au']")."""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + "\n")
        f.write("window.RODA_MOCAP = window.RODA_MOCAP || {};\n")
        f.write(var_expr + " = ")
        json.dump(obj, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    return path
