# /// script
# requires-python = ">=3.10"
# ///
"""
Move-library coverage report.

Cross-references sources.json (all 52 moves + compilations) against what
fetch_youtube.py actually downloaded (clips/manifest.json) and the pose
detection rate (out/index.json), then prints a per-category table and writes
COVERAGE.md. Answers: which moves have >=1 clip, and how well pose tracked it.

  uv run tools/mocap/coverage.py
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
for _s in (sys.stdout, sys.stderr):
    try: _s.reconfigure(encoding="utf-8", errors="replace")
    except Exception: pass


def load(path, default):
    try:
        with open(os.path.join(HERE, path), encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return default


CAT_LABEL = {"golpes": "Kicks", "esquivas": "Dodges",
             "floreios": "Acrobatics", "quedas": "Takedowns"}


def main():
    src = load("sources.json", {"moves": [], "compilations": []})
    moves = src["moves"]
    manifest = load("clips/manifest.json", [])
    index = load("out/index.json", [])

    det = {}  # file -> detection %
    for it in index:
        n, d = it.get("n") or 0, it.get("detected") or 0
        det[it["file"]] = round(100 * d / n) if n else 0

    # slug -> [(file, kind, det%, is_single)]
    cover = {m["slug"]: [] for m in moves}
    for rec in manifest:
        if not rec.get("yt_id"):
            continue
        file = rec.get("file")
        for slug in rec.get("moves", []):
            if slug in cover:
                cover[slug].append((file, rec.get("kind", "move"),
                                    det.get(file), rec.get("kind") == "move"))

    def best(entries):
        # prefer a dedicated single-move clip, then highest detection rate
        return sorted(entries, key=lambda e: (e[3], (e[2] or 0)), reverse=True)[0] if entries else None

    lines = ["# Move-library coverage", "",
             "Auto-generated by `tools/mocap/coverage.py`. ✓ = at least one clip "
             "covers the move; *det* is the share of sampled frames where pose "
             "estimation found a person (higher = cleaner source for retargeting).",
             ""]
    by_cat = {}
    for m in moves:
        by_cat.setdefault(m["cat"], []).append(m)

    tot_cov = tot = 0
    p1_cov = p1 = 0
    for cat in ("golpes", "esquivas", "floreios", "quedas"):
        ms = by_cat.get(cat, [])
        if not ms:
            continue
        lines.append(f"## {CAT_LABEL[cat]} ({cat})")
        lines.append("")
        lines.append("| move | | det | source | covered by |")
        lines.append("|---|---|---|---|---|")
        for m in ms:
            tot += 1
            if m["priority"] == 1:
                p1 += 1
            b = best(cover[m["slug"]])
            if b:
                tot_cov += 1
                if m["priority"] == 1:
                    p1_cov += 1
                file, kind, dp, _ = b
                dets = f"{dp}%" if dp is not None else "—"
                via = "dedicated" if kind == "move" else "compilation"
                lines.append(f"| {m['pt']} | ✓ | {dets} | `{file}` | {via} |")
            else:
                tag = "" if m["priority"] == 1 else " *(round 2)*"
                lines.append(f"| {m['pt']} | — | — | — | _missing_{tag} |")
        lines.append("")

    missing = [m for m in moves if not cover[m["slug"]]]
    summary = (f"**{tot_cov}/{tot} moves covered** "
               f"(priority-1: {p1_cov}/{p1}). "
               f"{len(missing)} remaining" +
               (": " + ", ".join(m["slug"] for m in missing) if missing else "."))
    lines.insert(4, summary)
    lines.insert(5, "")

    out = os.path.join(HERE, "COVERAGE.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(summary.replace("**", ""))
    print(f"\nWrote {os.path.relpath(out, os.path.dirname(HERE))}")


if __name__ == "__main__":
    main()
