"""Convert Natural Earth 110m land GeoJSON to a compact equirectangular SVG
path, written as assets/worldmap.js (window.WORLD_MAP). Public-domain source.

Projection (plate carrée / equirectangular) so marker lat/lng maps linearly:
    x = (lon + 180) * SCALE
    y = (LAT_MAX - lat) * SCALE
The map is cropped to LAT_MAX..LAT_MIN to drop Antarctica and dead space."""
import json, pathlib

SCALE = 4.0           # px per degree
LON_MIN, LON_MAX = -180.0, 180.0
LAT_MAX, LAT_MIN = 84.0, -56.0     # crop: Greenland down to Tierra del Fuego / NZ

W = round((LON_MAX - LON_MIN) * SCALE)   # 1440
H = round((LAT_MAX - LAT_MIN) * SCALE)   # 560

root = pathlib.Path(__file__).resolve().parent.parent
src = json.loads((root / "ne_110m_land.json").read_text(encoding="utf-8"))

def project(lon, lat):
    x = (lon - LON_MIN) * SCALE
    y = (LAT_MAX - lat) * SCALE
    return round(x), round(y)

def ring_path(ring):
    pts = []
    last = None
    for lon, lat in ring:
        p = project(lon, lat)
        if p != last:                 # drop consecutive duplicates after rounding
            pts.append(p)
            last = p
    if len(pts) < 3:
        return ""
    d = "M" + " L".join(f"{x},{y}" for x, y in pts) + "Z"
    return d

def polys(geom):
    t = geom["type"]
    if t == "Polygon":
        return geom["coordinates"]
    if t == "MultiPolygon":
        return [ring for poly in geom["coordinates"] for ring in poly]
    return []

paths = []
for feat in src["features"]:
    for ring in polys(feat["geometry"]):
        lats = [c[1] for c in ring]
        if max(lats) < LAT_MIN:       # skip Antarctica
            continue
        d = ring_path(ring)
        if d:
            paths.append(d)

land = "".join(paths)
out = (
    "/* Equirectangular world land outline (Natural Earth 110m, public domain).\n"
    "   Generated by tools/make_worldmap.py. Lat/lng project linearly:\n"
    "     x=(lon+180)*%g  y=(%g-lat)*%g  within viewBox 0 0 %d %d. */\n"
    "window.WORLD_MAP={w:%d,h:%d,scale:%g,lonMin:%g,latMax:%g,land:%s};\n"
) % (SCALE, LAT_MAX, SCALE, W, H, W, H, SCALE, LON_MIN, LAT_MAX, json.dumps(land))

(root / "assets" / "worldmap.js").write_text(out, encoding="utf-8")
print(f"viewBox 0 0 {W} {H}; {len(paths)} rings; {len(land)} path chars; "
      f"asset {len(out)} bytes")
